#
# Copyright 2021-2023 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

replicaCount: 1

image:
  # Check https://hub.docker.com/u/softwareradiosystems for available images
  repository: muriloavlis/srsran-5g
  pullPolicy: Always
  tag: "zmq_latest"

imagePullSecrets:
  - name: regcred

nameOverride: "srsran-gnb-zmq"
fullnameOverride: "srsran-gnb-zmq"

serviceAccount:
  create: true
  annotations: {}
  name: "srsadmin-gnb"

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    add: ["SYS_NICE", "NET_ADMIN"]
  privileged: true
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

network:
  hostNetwork: false

resources:
  {}
  # limits:
  #   cpu: 12
  #   memory: 16Gi
  #   hugepages-1Gi: 2Gi
  # requests:
  #   cpu: 12
  #   memory: 16Gi
  #   hugepages-1Gi: 2Gi

nodeSelector:
  kubernetes.io/hostname: ran5g

tolerations:
  {}
  # - key: "purpose"
  #   value: "manual-testing"
  #   operator: "Equal"
  #   effect: "NoSchedule"

affinity: {}

debugging:
  enabled: true
  storageCapacity: "100Mi"
  hostPath: "/mnt/debugging-logs"
  containerPath: "/tmp"

srsue:
  name: "srsue"
  image:
    repository: muriloavlis/srsran-ue
    tag: "latest"
    pullPolicy: Always
  config:
    usim:
      k: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      opc: "E8ED289DEBA952E4283B54E88E6183CA"
      imsi: "724700000000001"
      imei: "000000000000001"
    nas:
      apn: internet
      apn_protocol: ipv4v6

    slicing: ## Set to false to Open5GS core (Why???????)
      enable: false
      nssai_sst: 4
      nssai_sd: 000001

config:
  gnb_id: 0 # Optional UINT (411). Sets the numerical ID associated with the gNB.
  gnb_id_bit_length: 32 # Optional UNIT. Sets the bit length of the gnb_id above. Format: integer between [22 - 32]
  ran_node_name: srs_gnb_01 # Optional TEXT (srsgnb01). Sets the text ID associated with the gNB. Format: string without spaces.
  gnb_du_id: 0 # Optional UINT (0). Sets the gNB DU ID. Supported: [0 - 68719476735].

  amf:
    addr: open5gs-amf-ngap.open5gs # The address or hostname of the AMF.
    bind_addr: eth0 # A local IP that the gNB binds to for traffic from the AMF.
    port: 38412
    # no_core: true

  ru_sdr:
    device_driver: zmq
    device_args: tx_port=tcp://*:2000,rx_port=tcp://127.0.0.1:2001,id=srs_gnb,base_srate=23.04e6
    srate: 23.04
    tx_gain: 75
    rx_gain: 75

  disable_ru_ofh: true

  slicing:
    - sst: 1
      sd: 0x000001
    - sst: 2
      sd: 0x000001
    - sst: 3
      sd: 0x000001
    - sst: 4
      sd: 0x000001

  cell_cfg:
    dl_arfcn: 368500 # ARFCN of the downlink carrier (center frequency).
    band: 3 # The NR band.
    channel_bandwidth_MHz: 20 # Bandwith in MHz. Number of PRBs will be automatically derived.
    common_scs: 15 # Subcarrier spacing in kHz used for data.
    plmn: "72470" # PLMN broadcasted by the gNB.
    tac: 1 # Tracking area code (needs to match the core configuration).
    pci: 1 # Physical cell ID.
    nof_antennas_dl: 1
    nof_antennas_ul: 1

    pdcch:
      common:
        coreset0_index: 12 # Optional INT. Sets the CORESET 0 index. Supported: [0 - 15].
        ss0_index: 0 # Optional UINT (0). Sets the SearchSpace#0 index. Supported: [0 - 15].
      dedicated:
        dci_format_0_1_and_1_1: false # Optional BOOLEAN (true). Sets whether to use non-fallback or fallback DCI format in UE SearchSpace#2. Supported: [false, true].
        ss2_type: ue_dedicated # Optional TEXT (ue_dedicated). Sets the SearchSpace type for UE dedicated SearchSpace#2. Supported: [common, ue_dedicated].

    prach:
      prach_config_index: 1 # Sets PRACH config to match what is expected by srsUE

  e2:
    enable_du_e2: true # Enable DU E2 agent (one for each DU instance)
    e2sm_kpm_enabled: true # Enable KPM service module
    e2sm_rc_enabled: true # Enable KPM service module
    addr: service-ricplt-e2term-sctp-alpha.ricplt # RIC IP address or service name
    bind_addr: eth0 # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine.
    port: 36421 # RIC port

  log: # Set debugging->enabled->true in order to make logs persistent. Make sure hostPath and log file path match.
    filename: /tmp/gnb.log # Path of the log file.
    all_level: debug # Logging level applied to all layers.

  pcap:
    mac_enable: false # Set to true to enable MAC-layer PCAPs.
    mac_filename: /tmp/gnb_mac.pcap # Path where the MAC PCAP is stored.
    ngap_enable: false # Set to true to enable NGAP PCAPs.
    ngap_filename: /tmp/gnb_ngap.pcap # Path where the NGAP PCAP is stored.
    e2ap_enable: true # Set to true to enable E2AP PCAPs.
    e2ap_filename: /tmp/gnb_e2ap.pcap # Path where the E2AP PCAP is stored.

  metrics:
    autostart_stdout_metrics: true # Enable reporting metrics in stdout
    # enable_json_metrics: true        # Enable reporting metrics in JSON format
    # addr: 10.233.43.143              # Metrics-server IP
    # port: 55555                      # Metrics-server Port
