# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ricplt:
# This section is reserved for values imported from RIC Platform charts
  dbaasService: "service-ricplt-dbaas-tcp.ricplt.svc.cluster.local"
  metricsdbService: "service-metricsdb.ricplt.svc.cluster.local"
  pltIngressUrl: "ricplt-entry"
  xappIngressUrl: "ricxapp-entry"

  appmgrRMRService: "service-ricplt-appmgr-rmr.ricplt.svc.cluster.local"
  e2mgrRMRService: "service-ricplt-e2mgr-rmr.ricplt.svc.cluster.local"
  e2termRMRService: "service-ricplt-e2term-rmr.ricplt.svc.cluster.local"
  rtmgrRMRService: "service-ricplt-rtmgr-rmr.ricplt.svc.cluster.local"
  a1mediatorRMRService: "service-ricplt-a1mediator-rmr.ricplt.svc.cluster.local"

# Location of the xApp config files injected from the xApp descriptor
appconfig:
    path: /opt/ric/config

# Location of volume based on HostPath of type Directory
storage:
    mountPath: /home/kpm/storage

# Number of replica
replicaCount: 1

# Image pulling policy
image_pull_policy: IfNotPresent

# Environment variables that will be injected
appenv: {}

# Liveness probe definition. If empty, liveness probe will be disabled
livenessProbe: {}

# Readiness probe definition. If empty, readiness probe will be disabled
readinessProbe: {}

# Instance name. If empty, chart name will be used
name: {}

# Full instance name. If empty, full name will be constructed from name
fullname: {}

###############    The following are from the xApp descriptor     ###############
containers:
- image:
    name: muriloavlis/usap
    registry: docker.io
    tag: latest
  name: usap
controls:
  active: true
  interfaceId:
    globalGNBId:
      plmnId: 72470
  localAddress:
    host: :8080
  logger:
    level: 3
  measurement_interval: 1000
  subscription:
    subscriptionActive: true
coredb:
  dbname: oai_db
  hostname: mysql.oai5gcn
  password: test
  port: '3306'
  username: test
db:
  host: service-ricplt-dbaas-tcp.ricplt:6379
  maxActive: 100
  maxIdle: 50
  protocol: tcp
  waitForSdl: false
faults: {}
livenessProbe:
  httpGet:
    path: ric/v1/health/alive
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 15
measurements:
- description: 'UE Downlink Throughput '
  name: ricxapp_usap_xapp_DRBUEThpDl
  objectInstance: DRB.UEThpDl
  objectName: DRB.UEThpDl
  type: int
- description: UE Uplink Throughput
  name: ricxapp_usap_xapp_DRBUEThpUl
  objectInstance: DRB.UEThpUl
  objectName: DRB.UEThpUl
  type: int
messaging:
  ports:
  - container: usap-xapp
    description: http service
    name: http
    port: 8080
  - container: usap-xapp
    description: rmr route port for usap-xapp
    name: rmr-route
    port: 4561
  - container: usap-xapp
    description: rmr data port for usap-xapp
    maxSize: 65536
    name: rmrdata
    numWorkers: 1
    policies: []
    port: 4560
    protocol: tcp
    rxMessages:
    - RIC_SUB_RESP
    - RIC_SUB_FAILURE
    - RIC_SUB_DEL_RESP
    - RIC_INDICATION
    txMessages:
    - RIC_SUB_REQ
    - RIC_SUB_DEL_REQ
metrics:
  namespace: ricxapp
  url: /ric/v1/metrics
readinessProbe:
  httpGet:
    path: ric/v1/health/ready
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 15
vendor: Murilo Silva <murilosilva@itec.ufpa.br>
version: 0.0.1
xapp_name: usap-xapp

nodeSelector:
  kubernetes.io/hostname: nrtric