apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gtpu
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "srsran-cudu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.gtpu.type }}
  {{- if .Values.services.gtpu.sessionAffinity }}
  sessionAffinity: {{ .Values.services.gtpu.sessionAffinity }}
  {{- end }}
  {{- if .Values.services.gtpu.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.services.gtpu.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if and .Values.services.gtpu.clusterIP (eq .Values.services.gtpu.type "ClusterIP") }}
  clusterIP: {{ .Values.services.gtpu.clusterIP }}
  {{- end }}
  {{- if (and (eq .Values.services.gtpu.type "LoadBalancer") (not (empty .Values.services.gtpu.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.services.gtpu.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.services.gtpu.type "LoadBalancer") .Values.services.gtpu.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.services.gtpu.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.services.gtpu.type "LoadBalancer") (eq .Values.services.gtpu.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.services.gtpu.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - name: gtpu
      port: {{ .Values.services.gtpu.ports.gtpu }}
      protocol: UDP
      targetPort: gtpu
      {{- if and (or (eq .Values.services.gtpu.type "NodePort") (eq .Values.services.gtpu.type "LoadBalancer")) (not (empty .Values.services.gtpu.nodePorts.gtpu)) }}
      nodePort: {{ .Values.services.gtpu.nodePorts.gtpu }}
      {{- else if eq .Values.services.gtpu.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  publishNotReadyAddresses: true
  selector: {{- include "srsran-cudu.selectorLabels" . | nindent 4 }}