################################################################################
#   Copyright (c) 2019 AT&T Intellectual Property.                             #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
################################################################################'
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ricplt:
  # This section is reserved for values imported from RIC Platform charts
  dbaasService: "service-ricplt-dbaas-tcp.ricplt.svc.cluster.local"
  metricsdbService: "service-metricsdb.ricplt.svc.cluster.local"
  pltIngressUrl: "ricplt-entry"
  xappIngressUrl: "ricxapp-entry"

  appmgrRMRService: "service-ricplt-appmgr-rmr.ricplt.svc.cluster.local"
  e2mgrRMRService: "service-ricplt-e2mgr-rmr.ricplt.svc.cluster.local"
  e2mgrHttpService: "service-ricplt-e2mgr-http.ricplt.svc.cluster.local"
  e2termRMRService: "service-ricplt-e2term-rmr-alpha.ricplt.svc.cluster.local"
  rtmgrRMRService: "service-ricplt-rtmgr-rmr.ricplt.svc.cluster.local"
  a1mediatorRMRService: "service-ricplt-a1mediator-rmr.ricplt.svc.cluster.local"

# Python gRPC Encoder/Decoder
oranASN1Coder:
  name: usap-oranasn1coder
  containers:
    - image:
        repository: muriloavlis/usap-oranasn1coder
        registry: docker.io
        tag: latest
        imagePullPolicy: Always
      ports:
        - name: grpc-server
          containerPort: 5051
          protocol: TCP
  service:
    type: ClusterIP
    ports:
      - name: grpc-server
        port: 5051
        targetPort: 5051
        protocol: TCP

  grpcServerService: service-usap-oranasn1coder.ricxapp ## svc-name + namespace
  grpcPort: 5051

# Location of the xApp config files injected from the xApp descriptor
appconfig:
  path: /opt/ric/config

# Location of volume based on HostPath of type Directory
storage:
  mountPath: /home/kpm/storage

# Number of replica
replicaCount: 1

# Image pulling policy
image_pull_policy: Always

# Environment variables that will be injected
appenv: {}

# Full instance name. If empty, full name will be constructed from name
fullname: {}

###############    The following are from the xApp descriptor     ###############
appVersion: v1.0.0-alpha
containers:
  - image:
      name: muriloavlis/usap
      registry: docker.io
      tag: latest
    name: usap
controls:
  active: true
  interfaceId:
    globalGNBId:
      plmnId: 72470
  localAddress:
    host: :8080
  logger:
    level: 4 ## [1: ERR, 2: WARN, 3: INFO, 4:DEBUG]
  measurement_interval: 1000
  subscription:
    subscriptionActive: true
coredb:
  dbname: oai_db
  hostname: mysql.oai5gcn
  password: test
  port: "3306"
  username: test
db:
  maxActive: 100
  maxIdle: 50
  waitForSdl: false
faults: {}
livenessProbe:
  httpGet:
    path: ric/v1/health/alive
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 15
measurements:
  - description: "UE Downlink Throughput "
    name: ricxapp_usap_xapp_DRBUEThpDl
    objectInstance: DRB.UEThpDl
    objectName: DRB.UEThpDl
    type: int
  - description: UE Uplink Throughput
    name: ricxapp_usap_xapp_DRBUEThpUl
    objectInstance: DRB.UEThpUl
    objectName: DRB.UEThpUl
    type: int
messaging:
  ports:
    - name: http
      container: usap
      description: http service
      port: 8080
    - name: rmr-data
      container: usap
      description: rmr data port for usap
      maxSize: 65536
      numWorkers: 1
      policies: []
      port: 4560
      protocol: tcp
      rxMessages:
        - RIC_SUB_RESP
        - RIC_SUB_FAILURE
        - RIC_SUB_DEL_RESP
        - RIC_INDICATION
      txMessages:
        - RIC_SUB_REQ
        - RIC_SUB_DEL_REQ
    - name: rmr-route
      container: usap
      description: rmr route port for usap
      port: 4561
metrics:
  namespace: ricxapp
  url: /ric/v1/metrics
name: usap
readinessProbe:
  httpGet:
    path: ric/v1/health/ready
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 15
rmr:
  maxSize: 8192
  numWorkers: 1
  policies: []
  protPort: tcp:4560
  rxMessages:
    - RIC_SUB_RESP
    - RIC_INDICATION
    - RIC_HEALTH_CHECK_REQ
  txMessages:
    - RIC_SUB_REQ
    - RIC_HEALTH_CHECK_RESP
vendor: Murilo Silva <murilosilva@itec.ufpa.br>
version: 0.0.1
