apiVersion: v2
dependencies:
- name: nearrt-ric-common
  repository: '@local'
  version: ~0.x
description: Helm Chart for the E2 Termination for Near RT RIC Platform.
kubeVersion: ' >= 1.22'
name: e2term
sources:
- https://gerrit.o-ran-sc.org/r/admin/repos/ric-plt/e2,general
version: 0.1.0
