# Reference:- TS 29.531 R16.0.0., Section- 6.1.6 Data Model
info:
  version: 2.0.0
  description: OAI-NSSF Release v2.0.1
configuration:
  nsiInfoList:
    - snssai:
        sst: 1
        sd: "000001"
      nsiInformationList:
        nrfId: http://oai-cn5g-nrf-10.fr:80/nnrf-disc/v1/nf-instances
        nsiId: "1"
        nrfNfMgtUri: http://oai-cn5g-nrf-10.fr:80/nnrf-nfm/v1/nf-instances
    - snssai:
        sst: 2
        sd: "000001"
      nsiInformationList:
        nrfId: http://oai-cn5g-nrf-10.fr:80/nnrf-disc/v1/nf-instances
        nsiId: "2"
    - snssai:
        sst: 3
        sd: "000001"
      nsiInformationList:
        nrfId: http://oai-cn5g-nrf-20.fr:80/nnrf-disc/v1/nf-instances
        nsiId: "3"
    - snssai:
        sst: 128
        sd: "000001"
      nsiInformationList:
        nrfId: http://oai-cn5g-nrf-20.fr:80/nnrf-disc/v1/nf-instances
        nsiId: "4"
  taInfoList:
    - tai:
        plmnId:
          mcc: "724"
          mnc: "70"
        tac: "00001"
      supportedSnssaiList:
        - sst: 1
          sd: "000001"
        - sst: 2
          sd: "000001"
        - sst: 3
          sd: "000001"
        - sst: 128
          sd: "000001"
  amfInfoList:
    - targetAmfSet: 724-70-01-001
      nrfAmfSet: http://oai-cn5g-nrf.fr:80/nnrf-disc/v1/nf-instances'
      nrfAmfSetNfMgtUri: http://oai-cn5g-nrf.fr:80/nnrf-nfm/v1/nf-instances
      amfList:
        - nfId: 405e8251-cc5a-45dd-a494-efb9eaf1cd58
          supportedNssaiAvailabilityData:
            tai:
              plmnId:
                mcc: 724
                mnc: 70
              tac: 00001
            supportedSnssaiList:
              - sst: 1
                sd: "000001"
              - sst: 2
                sd: "000001"
              - sst: 3
                sd: "000001"
              - sst: 128
                sd: "000001"
  plmnInfoList:
    - operatorName: yoshisauro
      homePlmnId:
        mcc: 724
        mnc: 70
