apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "qmai.fullname" . }}-config
  namespace: riab
  labels: 
    app: {{ template "qmai.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  logging.yaml: |-
    {{- if .Values.logging }}
    {{ toYaml .Values.logging | indent 4 }}
    {{- end}}
  config.json: |-
    {{ .Values.config.qmai.configJson | toPrettyJson | indent 4 }}