apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qmai.fullname" . }}
  namespace: riab
  labels: 
    {{- include "qmai.labels" . | nindent 4 }}
  annotations:
      keel.sh/policy: "all"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ template "qmai.fullname" . }}
      resource: {{ template "qmai.fullname" . }}
  template:
    metadata:
      annotations:
        proxy.onosproject.org/inject: "true"
      labels:
        name: {{ template "qmai.fullname" . }}
        resource: {{ template "qmai.fullname" . }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "qmai.imagename" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-caPath=/etc/qmai/certs/tls.cacrt"
            - "-keyPath=/etc/qmai/certs/tls.key"
            - "-certPath=/etc/qmai/certs/tls.crt"
            - "-e2tEndpoint={{ .Values.config.qmai.e2tEndpoint }}"
            - "-smVersion={{ .Values.config.qmai.kpmVersion }}"
          ports:
            - name: grpc
              containerPort: {{ .Values.service.grpc.port }}
            - name: gnmi
              containerPort: {{ .Values.service.gnmi.port}}
          # startupProbe: ## TODO: creates a GRPC server in xApp
          #   tcpSocket:
          #     port: 5150
          #   periodSeconds: 5
          #   failureThreshold: 60
          # readinessProbe:
          #   tcpSocket:
          #     port: 5150
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          # livenessProbe:
          #   tcpSocket:
          #     port: 5150
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          volumeMounts:
            - name: secret
              mountPath: /etc/qmai/certs
              readOnly: true
            - name: config
              mountPath: /etc/qmai/config
              readOnly: true
          env:
            # *_NAMESPACE and *_NAME environment variables are recognized by onos-lib-go utilities.
            # These variables should always be defined.
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_NAME
              value: {{ template "qmai.fullname" . }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: secret
          secret:
            secretName: {{ template "qmai.fullname" . }}-secret
        - name: config
          configMap:
            name: {{ template "qmai.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}