apiVersion: v2
name: qmai
description: xApp for QoS Management by Artificial Intelligence (QMAI)
type: application
version: 0.0.1
appVersion: "latest"
keywords:
  - xApp
  - sdn
  - ric
  - QoS
home: http://gercom.ufpa.br
maintainers:
  - name: Murilo Silva
    email: murilosilva@itec.ufpa.br