#
# Copyright 2021-2023 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

replicaCount: 1

image:
  # Check https://hub.docker.com/u/softwareradiosystems for available images
  repository: softwareradiosystems/srsran-project
  pullPolicy: IfNotPresent
  tag: split72_release_avx512-latest

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: "srsran-du"

serviceAccount:
  create: true
  annotations: {}
  name: "srsadmin-du"

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    add: ["SYS_NICE", "NET_ADMIN"]
  privileged: true
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

network:
  hostNetwork: true

resources:
  enable_hugepages_1gi: true
  # enable_hugepages_2mi: false
  limits:
    cpu: 12
    memory: 16Gi
    hugepages-1Gi: 2Gi
  requests:
    cpu: 12
    memory: 16Gi
    hugepages-1Gi: 2Gi

nodeSelector: {}
  # kubernetes.io/hostname: node1

tolerations: {}
  # - key: "purpose"
  #   value: "manual-testing"
  #   operator: "Equal"
  #   effect: "NoSchedule"

affinity: {}

debugging:
  enabled: false
  storageCapacity: "100Mi"
  hostPath: "/mnt/debugging-logs"
  containerPath: "/tmp"

config:
  run_as: srsdu
  gnb-config.yml: |-
    gnb_id: 411                         # Optional UINT (411). Sets the numerical ID associated with the gNB.
    gnb_id_bit_length: 32               # Optional UNIT. Sets the bit length of the gnb_id above. Format: integer between [22 - 32]
    gnb_du_id: 0                        # Optional UINT (0). Sets the gNB DU ID. Supported: [0 - 68719476735].

    f1ap:                                  # Interface between DU and CU-CP
      cu_cp_addr: 127.0.0.1                # Required TEXT (127.0.10.1). Sets the CU-CP F1-C address to connect to. 
      bind_addr: 127.0.0.1                 # Required TEXT (127.0.10.2). Sets the DU F1-C bind address. If left empty, implicit bind is performed. 

    nru:                                    # Interface between CU and CU-UP
      queue_size: 2048                      # Optional INT (2048). Sets the F1-U PDU queue size in bytes. 
      bind_addr: 127.0.0.1                  # Required TEXT (127.0.10.2). Sets the DU F1-U bind address. If left empty, implicit bind is performed.

    ru_ofh:
      t1a_max_cp_dl: 420
      t1a_min_cp_dl: 250
      t1a_max_cp_ul: 420
      t1a_min_cp_ul: 250
      t1a_max_up: 196
      t1a_min_up: 80
      ta4_max: 500
      ta4_min: 25
      is_prach_cp_enabled: true
      ignore_ecpri_payload_size: true
      compr_method_ul: bfp
      compr_bitwidth_ul: 9
      compr_method_dl: bfp
      compr_bitwidth_dl: 9
      compr_method_prach: bfp
      compr_bitwidth_prach: 9
      enable_ul_static_compr_hdr: false
      enable_dl_static_compr_hdr: false
      iq_scaling: 0.75
      cells:
        - network_interface: "0000:b1:00.0"
          ru_mac_addr: 6c:ad:ad:00:0a:88
          du_mac_addr: 3C:EC:EF:B7:CE:68
          vlan_tag_cp: 163
          vlan_tag_up: 163
          prach_port_id: [4, 5, 6, 7]
          dl_port_id: [0, 1, 2, 3]
          ul_port_id: [0, 1, 2, 3]

    cell_cfg:
      dl_arfcn: 649980
      band: 78
      channel_bandwidth_MHz: 20
      common_scs: 30
      plmn: "00101"
      tac: 1
      pci: 1
      nof_antennas_dl: 4
      nof_antennas_ul: 4
      slicing:                                # Optional TEXT. Configure network slicing options. This can only be set via the configuration file :(
        - sst: 1                              
          sd: 16777215                        # 0xFFFFFF 
          sched_cfg:         
            min_prb_policy_ratio: 0           # Sets the minimum percentage of PRBs to be allocated to the slice. Supported [0 - 100].
            max_prb_policy_ratio: 100         # Sets the maximum percentage of PRBs to be allocated to the slice. Supported [1 - 100].

      prach:
        prach_config_index: 159
        prach_root_sequence_index: 1
        zero_correlation_zone: 0
        prach_frequency_start: 12
      tdd_ul_dl_cfg:
        dl_ul_tx_period: 10
        nof_dl_slots: 7
        nof_dl_symbols: 6
        nof_ul_slots: 2
        nof_ul_symbols: 4
      pdsch:
        mcs_table: qam256
      pusch:
        mcs_table: qam256

    hal:
      eal_args: "--lcores (0-1)@(0-23) -a 0000:b1:00.0"  # TEXT. EAL configuration parameters used to initialize DPDK.

    e2:
      enable_du_e2: false                   # BOOLEAN (false). Enables the DU E2 agent. Supported: [false, true].
      addr: 127.0.0.1                       # TEXT (127.0.0.1). Sets the RIC IP address.
      port: 36421                           # UINT (36421). Sets the RIC Port. Supported: [20000 - 40000].
      bind_addr: 127.0.0.1                  # TEXT (127.0.0.1). Sets the local IP address to bind for RIC connection. Supported: IPv4 address.
      e2sm_kpm_enabled: true                # BOOLEAN (false). Enabled the E2SM KPM service module. Supported: [false, true].
      e2sm_rc_enabled: true                 # BOOLEAN (false). Enabled the E2SM RC service module. Supported: [false, true].

    metrics:
      addr: 127.0.0.1                       # TEXT:IPV4 (127.0.0.1). Sets the metrics address. Supported: IPV4 address.
      port: 55555                           # UINT. Sets the metrics UPD port. Supported: [0 - 65535].
      rlc_report_period: 1000               # UINT (1000). Sets the RLC metrics report period in milliseconds. Supported [0 - inf]
      rlc_json_enable: true                 # BOOLEAN (false). Enable RLC metrics reporting (need to deliver measurements to E2SM_KPM service model).
      enable_json_metrics: false            # BOOLEAN (false). Enables JSON metrics reporting. Supported: [false, true].
      autostart_stdout_metrics: true        # BOOLEAN (false). Sets whether or note to autostart stdout metrics reporting. Supported [false, true].
      sched_report_period: 1000             # UINT (1). Sets the DU statistics report period in milliseconds. This metrics sets the console output period. Supported: [0 - inf].

    log:
      filename: /tmp/srsdu.log
      all_level: info

    pcap:
      mac_enable: false
      mac_filename: /tmp/gnb_mac.pcap
      f1ap_enable: false                  
      f1ap_filename: /tmp/gnb_f1ap.pcap   
      f1u_enable: false                   
      f1u_filename: /tmp/gnb_f1u.pcap     
      e2ap_enable: false                    
      e2ap_filename: /tmp/gnb_e2ap.pcap

