#
# Copyright 2021-2023 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

replicaCount: 1

image:
  # Check https://hub.docker.com/u/softwareradiosystems for available images
  repository: softwareradiosystems/srsran-project
  pullPolicy: IfNotPresent
  tag: split72_release_avx512-latest

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: "srsran-cu"

serviceAccount:
  create: true
  annotations: {}
  name: "srsadmin-cu"

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    add: ["SYS_NICE", "NET_ADMIN"]
  privileged: true
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

network:
  hostNetwork: true

resources: {}
  # limits:
  #   cpu: 12
  #   memory: 16Gi
  # requests:
  #   cpu: 12
  #   memory: 16Gi

nodeSelector: {}
  # kubernetes.io/hostname: node1

tolerations: {}
  # - key: "purpose"
  #   value: "manual-testing"
  #   operator: "Equal"
  #   effect: "NoSchedule"

affinity: {}

debugging:
  enabled: false
  storageCapacity: "100Mi"
  hostPath: "/mnt/debugging-logs"
  containerPath: "/tmp"

config:
  run_as: srscu
  gnb-config.yml: |-
    gnb_id: 411                         # Optional UINT (411). Sets the numerical ID associated with the gNB.
    gnb_id_bit_length: 32                 # Optional UNIT. Sets the bit length of the gnb_id above. Format: integer between [22 - 32]
    ran_node_name: cu_cp_01             # Optional TEXT (srsgnb01). Sets the text ID associated with the gNB. Format: string without spaces.

    cu_cp:
      amf:
        addr: 10.101.46.122
        port: 38412
        bind_addr: 10.21.2.2
        supported_tracking_areas:
          - tac: 1
            plmn_list:
              - plmn: "00101"
                tai_slice_support_list:
                  - sst: 1
                    sd: 16777215 # 0xFFFFFF

      f1ap:
        bind_addr: 127.0.0.1                 # Optional TEXT (127.0.0.1). Sets the F1-c bind address.
        procedure_timeout: 1000               # Optional INT (1000). Sets the UE context setup timeout in milliseconds.

    cu_up:
      gtpu_queue_size: 2048                   # INT (2048). Sets the GTP-U queue size, in PDUs.
      gtpu_reordering_timer: 0                # INT (0). Sets the GTP-U RX reordering timer (in milliseconds).
      warn_on_drop: false                     # BOOLEAN (false). Enables the option to log a warning for dropped packets in GTP-U and PDCP due to full queues. Supported: [false, true].

      upf:
        bind_addr: auto                       # TEXT (auto). Sets local IP address to bind for N3 interface. Format: IPV4 or IPV6 IP address.
        bind_interface: auto                  # TEXT (auto). Sets network device to bind for N3 interface. Format: IPV4 or IPV6 IP address.
        ext_addr: auto                        # TEXT (auto). Sets external IP address that is advertised to receive GTP-U packets from UPF via N3 interface. Format: IPV4 or IPV6 IP address.
        udp_max_rx_msgs: 256                  # INT (256). Sets the maximum amount of messages RX in a single syscall.
        pool_threshold: 0.9                   # FLOAT (0.9). Sets the pool accupancy threshold after which packets are dropped. Supported: [0.0 - 1.0].
        no_core: false                        # BOOLEAN (false). Setting to true allows the gNB to run without a core. Supported: [0, 1].

      nru:                             
        bind_addr: 127.0.0.1                 # TEXT (127.0.10.1). Sets the bind address used by the F1-U interface.
        ext_addr:                             # TEXT. Set the external IP address that is advertised to receive F1-U packets from the DU.     
        udp_max_rx_msgs: 256                  # INT (256). Sets the max number of UDP packets received by a single syscall on the F1-U interface.
        pool_threshold:                       # FLOAT. Sets the pool occupancy threshold after which packets are dropped. Supported: [0 - 1]. 

    e2:
      enable_cu_e2: false                   # BOOLEAN (false). Enables the CU E2 agent for both CU-cp and CU-up. Supported: [false, true]. 
      addr: 127.0.0.1                       # TEXT (127.0.0.1). Sets the RIC IP address.
      port: 36421                           # UINT (36421). Sets the RIC Port. Supported: [20000 - 40000].
      bind_addr: 127.0.0.1                  # TEXT (127.0.0.1). Sets the local IP address to bind for RIC connection. Supported: IPv4 address.
      e2sm_kpm_enabled: true                # BOOLEAN (false). Enabled the E2SM KPM service module. Supported: [false, true].
      e2sm_rc_enabled: true                 # BOOLEAN (false). Enabled the E2SM RC service module. Supported: [false, true].

    metrics:
      cu_cp_statistics_report_period: 1     # UINT (1). Sets the CU-CP statistics report period in seconds. Set this value to 0 to disable this feature. Supported: [0 - inf].
      cu_up_statistics_report_period: 1     # UINT (1). Sets the CU-UP statistics report period in seconds. Set this value to 0 to disable this feature. Supported: [0 - inf].
      pdcp_report_period: 1000              # UINT (0). Sets the PDCP metrics report period in milliseconds. Supported [0 - inf]

    log:
      filename: /tmp/srscu.log
      all_level: info

    pcap:
      ngap_enable: false
      ngap_filename: /tmp/gnb_ngap.pcap
      e2ap_enable: false                    
      e2ap_filename: /tmp/gnb_e2ap.pcap
      f1ap_enable: false
      f1ap_filename: /tmp/gnb_f1ap.pcap  