{{- $topCtx :=  . }}
{{- range .Values.messaging.ports  }}
{{- if contains "rmr" .name }}
{{ else }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ricxapp.servicename" $topCtx }}-{{ .name }}
  namespace: {{ include "ricxapp.namespace" $topCtx }}
  labels:
    app: {{ include "ricxapp.namespace" $topCtx }}-{{ include "ricxapp.name" $topCtx }}
    chart: {{ $topCtx.Chart.Name }}-{{ $topCtx.Chart.Version | replace "+" "_" }}
    release: {{ $topCtx.Release.Name }}
    heritage: {{ $topCtx.Release.Service }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
      name: {{ .name }}
  selector:
    app: {{ include "ricxapp.namespace" $topCtx }}-{{ include "ricxapp.name" $topCtx }}
    release: {{ $topCtx.Release.Name }}
{{- end }}
{{- end }}