apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.ingressname.appmgr" . }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: {{ include "common.kongpath.ric.appmgr" . }}(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "common.servicename.appmgr.http" . }}
            port:
              number: {{ include "common.serviceport.appmgr.http" . }}
