# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import e2sm_pb2 as e2sm__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in e2sm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventTriggerDefinitionStub(object):
    """------------------------------------//
    ------------- Services ------------//
    ----------------------------------//

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EncodeEventTriggerDefFormat1 = channel.unary_unary(
            '/usap_e2sm.EventTriggerDefinition/EncodeEventTriggerDefFormat1',
            request_serializer=e2sm__pb2.EncodeEventTriggerRequest.SerializeToString,
            response_deserializer=e2sm__pb2.EncodeEventTriggerResponse.FromString,
            _registered_method=True)


class EventTriggerDefinitionServicer(object):
    """------------------------------------//
    ------------- Services ------------//
    ----------------------------------//

    """

    def EncodeEventTriggerDefFormat1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventTriggerDefinitionServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'EncodeEventTriggerDefFormat1': grpc.unary_unary_rpc_method_handler(
            servicer.EncodeEventTriggerDefFormat1,
            request_deserializer=e2sm__pb2.EncodeEventTriggerRequest.FromString,
            response_serializer=e2sm__pb2.EncodeEventTriggerResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'usap_e2sm.EventTriggerDefinition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        'usap_e2sm.EventTriggerDefinition', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.


class EventTriggerDefinition(object):
    """------------------------------------//
    ------------- Services ------------//
    ----------------------------------//

    """

    @staticmethod
    def EncodeEventTriggerDefFormat1(request,
                                     target,
                                     options=(),
                                     channel_credentials=None,
                                     call_credentials=None,
                                     insecure=False,
                                     compression=None,
                                     wait_for_ready=None,
                                     timeout=None,
                                     metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usap_e2sm.EventTriggerDefinition/EncodeEventTriggerDefFormat1',
            e2sm__pb2.EncodeEventTriggerRequest.SerializeToString,
            e2sm__pb2.EncodeEventTriggerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RanFunctionDefinitionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DecodeRanFunctionDefinition = channel.unary_unary(
            '/usap_e2sm.RanFunctionDefinition/DecodeRanFunctionDefinition',
            request_serializer=e2sm__pb2.DecodeRanFunctionRequest.SerializeToString,
            response_deserializer=e2sm__pb2.DecodeRanFunctionResponse.FromString,
            _registered_method=True)


class RanFunctionDefinitionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DecodeRanFunctionDefinition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RanFunctionDefinitionServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'DecodeRanFunctionDefinition': grpc.unary_unary_rpc_method_handler(
            servicer.DecodeRanFunctionDefinition,
            request_deserializer=e2sm__pb2.DecodeRanFunctionRequest.FromString,
            response_serializer=e2sm__pb2.DecodeRanFunctionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'usap_e2sm.RanFunctionDefinition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        'usap_e2sm.RanFunctionDefinition', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.


class RanFunctionDefinition(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DecodeRanFunctionDefinition(request,
                                    target,
                                    options=(),
                                    channel_credentials=None,
                                    call_credentials=None,
                                    insecure=False,
                                    compression=None,
                                    wait_for_ready=None,
                                    timeout=None,
                                    metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usap_e2sm.RanFunctionDefinition/DecodeRanFunctionDefinition',
            e2sm__pb2.DecodeRanFunctionRequest.SerializeToString,
            e2sm__pb2.DecodeRanFunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ActionDefinitionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EncodeActionDefinitionFormat4 = channel.unary_unary(
            '/usap_e2sm.ActionDefinition/EncodeActionDefinitionFormat4',
            request_serializer=e2sm__pb2.EncodeActDefFormat4Request.SerializeToString,
            response_deserializer=e2sm__pb2.EncActDefResponse.FromString,
            _registered_method=True)


class ActionDefinitionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EncodeActionDefinitionFormat4(self, request, context):
        """TODO: implement for others formats
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActionDefinitionServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'EncodeActionDefinitionFormat4': grpc.unary_unary_rpc_method_handler(
            servicer.EncodeActionDefinitionFormat4,
            request_deserializer=e2sm__pb2.EncodeActDefFormat4Request.FromString,
            response_serializer=e2sm__pb2.EncActDefResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'usap_e2sm.ActionDefinition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        'usap_e2sm.ActionDefinition', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.


class ActionDefinition(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EncodeActionDefinitionFormat4(request,
                                      target,
                                      options=(),
                                      channel_credentials=None,
                                      call_credentials=None,
                                      insecure=False,
                                      compression=None,
                                      wait_for_ready=None,
                                      timeout=None,
                                      metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usap_e2sm.ActionDefinition/EncodeActionDefinitionFormat4',
            e2sm__pb2.EncodeActDefFormat4Request.SerializeToString,
            e2sm__pb2.EncActDefResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
