# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: e2sm.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'e2sm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ne2sm.proto\x12\tusap_e2sm\"4\n\x19\x45ncodeEventTriggerRequest\x12\x17\n\x0freportingPeriod\x18\x01 \x01(\x03\"5\n\x1a\x45ncodeEventTriggerResponse\x12\x17\n\x0f\x65ventTriggerDef\x18\x01 \x03(\x03\"5\n\x18\x44\x65\x63odeRanFunctionRequest\x12\x19\n\x11ranFuncDefinition\x18\x01 \x01(\t\"6\n\x19\x44\x65\x63odeRanFunctionResponse\x12\x19\n\x11\x64\x65\x63odedRanFuncDef\x18\x01 \x01(\t\"\xaa\x01\n\rTestCondValue\x12\x12\n\x08valueInt\x18\x02 \x01(\x03H\x00\x12\x13\n\tvalueEnum\x18\x03 \x01(\x03H\x00\x12\x13\n\tvalueBool\x18\x04 \x01(\x08H\x00\x12\x13\n\tvalueBitS\x18\x05 \x01(\x0cH\x00\x12\x13\n\tvalueOctS\x18\x06 \x01(\x0cH\x00\x12\x13\n\tvaluePrtS\x18\x07 \x01(\tH\x00\x12\x13\n\tvalueReal\x18\x08 \x01(\x01H\x00\x42\x07\n\x05value\"c\n\x0cTestCondInfo\x12\x10\n\x08testType\x18\x01 \x01(\t\x12\x10\n\x08testExpr\x18\x02 \x01(\t\x12/\n\rtestCondValue\x18\x03 \x01(\x0b\x32\x18.usap_e2sm.TestCondValue\"@\n\x0fMatchingUEConds\x12-\n\x0ctestCondInfo\x18\x01 \x01(\x0b\x32\x17.usap_e2sm.TestCondInfo\"\x82\x01\n\x1a\x45ncodeActDefFormat4Request\x12\x33\n\x0fmatchingUEConds\x18\x01 \x01(\x0b\x32\x1a.usap_e2sm.MatchingUEConds\x12\x14\n\x0cmeasNameList\x18\x02 \x03(\t\x12\x19\n\x11granularityPeriod\x18\x03 \x01(\x03\"0\n\x11\x45ncActDefResponse\x12\x1b\n\x13\x61\x63tionDefinitionEnc\x18\x01 \x03(\x03\x32\x85\x01\n\x16\x45ventTriggerDefinition\x12k\n\x1c\x45ncodeEventTriggerDefFormat1\x12$.usap_e2sm.EncodeEventTriggerRequest\x1a%.usap_e2sm.EncodeEventTriggerResponse2\x81\x01\n\x15RanFunctionDefinition\x12h\n\x1b\x44\x65\x63odeRanFunctionDefinition\x12#.usap_e2sm.DecodeRanFunctionRequest\x1a$.usap_e2sm.DecodeRanFunctionResponse2x\n\x10\x41\x63tionDefinition\x12\x64\n\x1d\x45ncodeActionDefinitionFormat4\x12%.usap_e2sm.EncodeActDefFormat4Request\x1a\x1c.usap_e2sm.EncActDefResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'e2sm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_ENCODEEVENTTRIGGERREQUEST']._serialized_start=25
  _globals['_ENCODEEVENTTRIGGERREQUEST']._serialized_end=77
  _globals['_ENCODEEVENTTRIGGERRESPONSE']._serialized_start=79
  _globals['_ENCODEEVENTTRIGGERRESPONSE']._serialized_end=132
  _globals['_DECODERANFUNCTIONREQUEST']._serialized_start=134
  _globals['_DECODERANFUNCTIONREQUEST']._serialized_end=187
  _globals['_DECODERANFUNCTIONRESPONSE']._serialized_start=189
  _globals['_DECODERANFUNCTIONRESPONSE']._serialized_end=243
  _globals['_TESTCONDVALUE']._serialized_start=246
  _globals['_TESTCONDVALUE']._serialized_end=416
  _globals['_TESTCONDINFO']._serialized_start=418
  _globals['_TESTCONDINFO']._serialized_end=517
  _globals['_MATCHINGUECONDS']._serialized_start=519
  _globals['_MATCHINGUECONDS']._serialized_end=583
  _globals['_ENCODEACTDEFFORMAT4REQUEST']._serialized_start=586
  _globals['_ENCODEACTDEFFORMAT4REQUEST']._serialized_end=716
  _globals['_ENCACTDEFRESPONSE']._serialized_start=718
  _globals['_ENCACTDEFRESPONSE']._serialized_end=766
  _globals['_EVENTTRIGGERDEFINITION']._serialized_start=769
  _globals['_EVENTTRIGGERDEFINITION']._serialized_end=902
  _globals['_RANFUNCTIONDEFINITION']._serialized_start=905
  _globals['_RANFUNCTIONDEFINITION']._serialized_end=1034
  _globals['_ACTIONDEFINITION']._serialized_start=1036
  _globals['_ACTIONDEFINITION']._serialized_end=1156
# @@protoc_insertion_point(module_scope)
