/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm-kpm-v4.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_BinRangeItem_H_
#define	_BinRangeItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BinIndex.h"
#include "BinRangeValue.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BinRangeItem */
typedef struct BinRangeItem {
	BinIndex_t	 binIndex;
	BinRangeValue_t	 startValue;
	BinRangeValue_t	 endValue;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BinRangeItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BinRangeItem;

#ifdef __cplusplus
}
#endif

#endif	/* _BinRangeItem_H_ */
#include <asn_internal.h>
