/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm-kpm-v4.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#include "BinRangeValue.h"

static asn_TYPE_member_t asn_MBR_BinRangeValue_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BinRangeValue, choice.valueInt),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"valueInt"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BinRangeValue, choice.valueReal),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"valueReal"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_BinRangeValue_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* valueInt */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* valueReal */
};
static asn_CHOICE_specifics_t asn_SPC_BinRangeValue_specs_1 = {
	sizeof(struct BinRangeValue),
	offsetof(struct BinRangeValue, _asn_ctx),
	offsetof(struct BinRangeValue, present),
	sizeof(((struct BinRangeValue *)0)->present),
	asn_MAP_BinRangeValue_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_BinRangeValue = {
	"BinRangeValue",
	"BinRangeValue",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_BinRangeValue_1,
	2,	/* Elements count */
	&asn_SPC_BinRangeValue_specs_1	/* Additional specs */
};

