/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm-kpm-v4.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_BinRangeDefinition_H_
#define	_BinRangeDefinition_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BinRangeList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BinRangeList;

/* BinRangeDefinition */
typedef struct BinRangeDefinition {
	BinRangeList_t	 binRangeListX;
	struct BinRangeList	*binRangeListY	/* OPTIONAL */;
	struct BinRangeList	*binRangeListZ	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BinRangeDefinition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BinRangeDefinition;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BinRangeList.h"

#endif	/* _BinRangeDefinition_H_ */
#include <asn_internal.h>
