/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../e2sm_v5.00/e2sm-v5.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#include "CoreCPID.h"

static asn_TYPE_member_t asn_MBR_CoreCPID_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CoreCPID, choice.fiveGC),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GUAMI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"fiveGC"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CoreCPID, choice.ePC),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GUMMEI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"ePC"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_CoreCPID_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fiveGC */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ePC */
};
static asn_CHOICE_specifics_t asn_SPC_CoreCPID_specs_1 = {
	sizeof(struct CoreCPID),
	offsetof(struct CoreCPID, _asn_ctx),
	offsetof(struct CoreCPID, present),
	sizeof(((struct CoreCPID *)0)->present),
	asn_MAP_CoreCPID_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CoreCPID = {
	"CoreCPID",
	"CoreCPID",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_CoreCPID_1,
	2,	/* Elements count */
	&asn_SPC_CoreCPID_specs_1	/* Additional specs */
};

