/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm-kpm-v4.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_DistMeasurementBinRangeList_H_
#define	_DistMeasurementBinRangeList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DistMeasurementBinRangeItem;

/* DistMeasurementBinRangeList */
typedef struct DistMeasurementBinRangeList {
	A_SEQUENCE_OF(struct DistMeasurementBinRangeItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DistMeasurementBinRangeList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DistMeasurementBinRangeList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DistMeasurementBinRangeItem.h"

#endif	/* _DistMeasurementBinRangeList_H_ */
#include <asn_internal.h>
