/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm-kpm-v4.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_E2SM_KPM_ActionDefinition_Format4_H_
#define	_E2SM_KPM_ActionDefinition_Format4_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MatchingUeCondPerSubList.h"
#include "E2SM-KPM-ActionDefinition-Format1.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* E2SM-KPM-ActionDefinition-Format4 */
typedef struct E2SM_KPM_ActionDefinition_Format4 {
	MatchingUeCondPerSubList_t	 matchingUeCondList;
	E2SM_KPM_ActionDefinition_Format1_t	 subscriptionInfo;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_KPM_ActionDefinition_Format4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_KPM_ActionDefinition_Format4;

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_KPM_ActionDefinition_Format4_H_ */
#include <asn_internal.h>
