/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../e2sm_v5.00/e2sm-v5.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_GlobalGNB_ID_H_
#define	_GlobalGNB_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMNIdentity.h"
#include "GNB-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GlobalGNB-ID */
typedef struct GlobalGNB_ID {
	PLMNIdentity_t	 pLMNIdentity;
	GNB_ID_t	 gNB_ID;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GlobalGNB_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GlobalGNB_ID;

#ifdef __cplusplus
}
#endif

#endif	/* _GlobalGNB_ID_H_ */
#include <asn_internal.h>
