/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../e2sm_v5.00/e2sm-v5.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_GlobalNGRANNodeID_H_
#define	_GlobalNGRANNodeID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GlobalGNB-ID.h"
#include "GlobalNgENB-ID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GlobalNGRANNodeID_PR {
	GlobalNGRANNodeID_PR_NOTHING,	/* No components present */
	GlobalNGRANNodeID_PR_gNB,
	GlobalNGRANNodeID_PR_ng_eNB,
	/* Extensions may appear below */
	
} GlobalNGRANNodeID_PR;

/* GlobalNGRANNodeID */
typedef struct GlobalNGRANNodeID {
	GlobalNGRANNodeID_PR present;
	union GlobalNGRANNodeID_u {
		GlobalGNB_ID_t	 gNB;
		GlobalNgENB_ID_t	 ng_eNB;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GlobalNGRANNodeID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GlobalNGRANNodeID;

#ifdef __cplusplus
}
#endif

#endif	/* _GlobalNGRANNodeID_H_ */
#include <asn_internal.h>
