/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../e2sm_v5.00/e2sm-v5.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#include "GUAMI.h"

static asn_TYPE_member_t asn_MBR_GUAMI_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GUAMI, pLMNIdentity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PLMNIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"pLMNIdentity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GUAMI, aMFRegionID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AMFRegionID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"aMFRegionID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GUAMI, aMFSetID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AMFSetID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"aMFSetID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GUAMI, aMFPointer),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AMFPointer,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"aMFPointer"
		},
};
static const ber_tlv_tag_t asn_DEF_GUAMI_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GUAMI_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pLMNIdentity */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* aMFRegionID */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* aMFSetID */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* aMFPointer */
};
static asn_SEQUENCE_specifics_t asn_SPC_GUAMI_specs_1 = {
	sizeof(struct GUAMI),
	offsetof(struct GUAMI, _asn_ctx),
	asn_MAP_GUAMI_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GUAMI = {
	"GUAMI",
	"GUAMI",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GUAMI_tags_1,
	sizeof(asn_DEF_GUAMI_tags_1)
		/sizeof(asn_DEF_GUAMI_tags_1[0]), /* 1 */
	asn_DEF_GUAMI_tags_1,	/* Same as above */
	sizeof(asn_DEF_GUAMI_tags_1)
		/sizeof(asn_DEF_GUAMI_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GUAMI_1,
	4,	/* Elements count */
	&asn_SPC_GUAMI_specs_1	/* Additional specs */
};

