/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../e2sm_v5.00/e2sm-v5.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_InterfaceID_Xn_H_
#define	_InterfaceID_Xn_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GlobalNGRANNodeID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InterfaceID-Xn */
typedef struct InterfaceID_Xn {
	GlobalNGRANNodeID_t	 global_NG_RAN_ID;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterfaceID_Xn_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterfaceID_Xn;

#ifdef __cplusplus
}
#endif

#endif	/* _InterfaceID_Xn_H_ */
#include <asn_internal.h>
