/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm-kpm-v4.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_LabelInfoList_H_
#define	_LabelInfoList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LabelInfoItem;

/* LabelInfoList */
typedef struct LabelInfoList {
	A_SEQUENCE_OF(struct LabelInfoItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LabelInfoList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LabelInfoList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LabelInfoItem.h"

#endif	/* _LabelInfoList_H_ */
#include <asn_internal.h>
