/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm-kpm-v4.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#include "MatchingUEidPerGP-Item.h"

static int
noUEmatched_3_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
noUEmatched_3_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
noUEmatched_3_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	noUEmatched_3_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
noUEmatched_3_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	noUEmatched_3_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
noUEmatched_3_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	noUEmatched_3_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
noUEmatched_3_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	noUEmatched_3_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
noUEmatched_3_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	noUEmatched_3_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
noUEmatched_3_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	noUEmatched_3_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static const asn_INTEGER_enum_map_t asn_MAP_noUEmatched_value2enum_3[] = {
	{ 0,	4,	"true" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_noUEmatched_enum2value_3[] = {
	0	/* true(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_noUEmatched_specs_3 = {
	asn_MAP_noUEmatched_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_noUEmatched_enum2value_3,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	2,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_noUEmatched_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_noUEmatched_3 = {
	"noUEmatched",
	"noUEmatched",
	noUEmatched_3_free,
	noUEmatched_3_print,
	noUEmatched_3_constraint,
	noUEmatched_3_decode_ber,
	noUEmatched_3_encode_der,
	noUEmatched_3_decode_xer,
	noUEmatched_3_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_noUEmatched_tags_3,
	sizeof(asn_DEF_noUEmatched_tags_3)
		/sizeof(asn_DEF_noUEmatched_tags_3[0]) - 1, /* 1 */
	asn_DEF_noUEmatched_tags_3,	/* Same as above */
	sizeof(asn_DEF_noUEmatched_tags_3)
		/sizeof(asn_DEF_noUEmatched_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_noUEmatched_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_matchedPerGP_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MatchingUEidPerGP_Item__matchedPerGP, choice.noUEmatched),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_noUEmatched_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"noUEmatched"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MatchingUEidPerGP_Item__matchedPerGP, choice.oneOrMoreUEmatched),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MatchingUEidList_PerGP,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"oneOrMoreUEmatched"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_matchedPerGP_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* noUEmatched */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* oneOrMoreUEmatched */
};
static asn_CHOICE_specifics_t asn_SPC_matchedPerGP_specs_2 = {
	sizeof(struct MatchingUEidPerGP_Item__matchedPerGP),
	offsetof(struct MatchingUEidPerGP_Item__matchedPerGP, _asn_ctx),
	offsetof(struct MatchingUEidPerGP_Item__matchedPerGP, present),
	sizeof(((struct MatchingUEidPerGP_Item__matchedPerGP *)0)->present),
	asn_MAP_matchedPerGP_tag2el_2,
	2,	/* Count of tags in the map */
	0,
	2	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_matchedPerGP_2 = {
	"matchedPerGP",
	"matchedPerGP",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_matchedPerGP_2,
	2,	/* Elements count */
	&asn_SPC_matchedPerGP_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_MatchingUEidPerGP_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MatchingUEidPerGP_Item, matchedPerGP),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_matchedPerGP_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"matchedPerGP"
		},
};
static const ber_tlv_tag_t asn_DEF_MatchingUEidPerGP_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MatchingUEidPerGP_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* matchedPerGP */
};
static asn_SEQUENCE_specifics_t asn_SPC_MatchingUEidPerGP_Item_specs_1 = {
	sizeof(struct MatchingUEidPerGP_Item),
	offsetof(struct MatchingUEidPerGP_Item, _asn_ctx),
	asn_MAP_MatchingUEidPerGP_Item_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	0,	/* Start extensions */
	2	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MatchingUEidPerGP_Item = {
	"MatchingUEidPerGP-Item",
	"MatchingUEidPerGP-Item",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MatchingUEidPerGP_Item_tags_1,
	sizeof(asn_DEF_MatchingUEidPerGP_Item_tags_1)
		/sizeof(asn_DEF_MatchingUEidPerGP_Item_tags_1[0]), /* 1 */
	asn_DEF_MatchingUEidPerGP_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_MatchingUEidPerGP_Item_tags_1)
		/sizeof(asn_DEF_MatchingUEidPerGP_Item_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MatchingUEidPerGP_Item_1,
	1,	/* Elements count */
	&asn_SPC_MatchingUEidPerGP_Item_specs_1	/* Additional specs */
};

