/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm-kpm-v4.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_MatchingCondList_H_
#define	_MatchingCondList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MatchingCondItem;

/* MatchingCondList */
typedef struct MatchingCondList {
	A_SEQUENCE_OF(struct MatchingCondItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MatchingCondList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MatchingCondList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MatchingCondItem.h"

#endif	/* _MatchingCondList_H_ */
#include <asn_internal.h>
