/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm-kpm-v4.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_MeasValueReportCond_H_
#define	_MeasValueReportCond_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MeasValueTestCond-Expression.h"
#include "TestCond-Value.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasValueReportCond */
typedef struct MeasValueReportCond {
	MeasValueTestCond_Expression_t	 testExpr;
	TestCond_Value_t	 testValue;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasValueReportCond_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasValueReportCond;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasValueReportCond_H_ */
#include <asn_internal.h>
