/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm-kpm-v4.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_MeasurementRecordItem_H_
#define	_MeasurementRecordItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeReal.h>
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasurementRecordItem_PR {
	MeasurementRecordItem_PR_NOTHING,	/* No components present */
	MeasurementRecordItem_PR_integer,
	MeasurementRecordItem_PR_real,
	MeasurementRecordItem_PR_noValue,
	/* Extensions may appear below */
	MeasurementRecordItem_PR_notSatisfied
} MeasurementRecordItem_PR;

/* MeasurementRecordItem */
typedef struct MeasurementRecordItem {
	MeasurementRecordItem_PR present;
	union MeasurementRecordItem_u {
		unsigned long	 integer;
		double	 real;
		NULL_t	 noValue;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		NULL_t	 notSatisfied;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasurementRecordItem_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_integer_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementRecordItem;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementRecordItem_H_ */
#include <asn_internal.h>
