/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm-kpm-v4.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_MeasurementTypeID_H_
#define	_MeasurementTypeID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasurementTypeID */
typedef long	 MeasurementTypeID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementTypeID;
asn_struct_free_f MeasurementTypeID_free;
asn_struct_print_f MeasurementTypeID_print;
asn_constr_check_f MeasurementTypeID_constraint;
ber_type_decoder_f MeasurementTypeID_decode_ber;
der_type_encoder_f MeasurementTypeID_encode_der;
xer_type_decoder_f MeasurementTypeID_decode_xer;
xer_type_encoder_f MeasurementTypeID_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementTypeID_H_ */
#include <asn_internal.h>
