/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm-kpm-v4.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_MeasurementCondItem_H_
#define	_MeasurementCondItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MeasurementType.h"
#include "MatchingCondList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BinRangeDefinition;

/* MeasurementCondItem */
typedef struct MeasurementCondItem {
	MeasurementType_t	 measType;
	MatchingCondList_t	 matchingCond;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct BinRangeDefinition	*binRangeDef	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasurementCondItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementCondItem;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BinRangeDefinition.h"

#endif	/* _MeasurementCondItem_H_ */
#include <asn_internal.h>
