/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../e2sm_v5.00/e2sm-v5.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_NG_RANnodeUEXnAPID_H_
#define	_NG_RANnodeUEXnAPID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NG-RANnodeUEXnAPID */
typedef unsigned long	 NG_RANnodeUEXnAPID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NG_RANnodeUEXnAPID;
asn_struct_free_f NG_RANnodeUEXnAPID_free;
asn_struct_print_f NG_RANnodeUEXnAPID_print;
asn_constr_check_f NG_RANnodeUEXnAPID_constraint;
ber_type_decoder_f NG_RANnodeUEXnAPID_decode_ber;
der_type_encoder_f NG_RANnodeUEXnAPID_encode_der;
xer_type_decoder_f NG_RANnodeUEXnAPID_decode_xer;
xer_type_encoder_f NG_RANnodeUEXnAPID_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NG_RANnodeUEXnAPID_H_ */
#include <asn_internal.h>
