/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../e2sm_v5.00/e2sm-v5.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_NR_CGI_H_
#define	_NR_CGI_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMNIdentity.h"
#include "NRCellIdentity.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NR-CGI */
typedef struct NR_CGI {
	PLMNIdentity_t	 pLMNIdentity;
	NRCellIdentity_t	 nRCellIdentity;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NR_CGI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NR_CGI;

#ifdef __cplusplus
}
#endif

#endif	/* _NR_CGI_H_ */
#include <asn_internal.h>
