/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../e2sm_v5.00/e2sm-v5.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_NRCellIdentity_H_
#define	_NRCellIdentity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NRCellIdentity */
typedef BIT_STRING_t	 NRCellIdentity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRCellIdentity;
asn_struct_free_f NRCellIdentity_free;
asn_struct_print_f NRCellIdentity_print;
asn_constr_check_f NRCellIdentity_constraint;
ber_type_decoder_f NRCellIdentity_decode_ber;
der_type_encoder_f NRCellIdentity_encode_der;
xer_type_decoder_f NRCellIdentity_decode_xer;
xer_type_encoder_f NRCellIdentity_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NRCellIdentity_H_ */
#include <asn_internal.h>
