/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../e2sm_v5.00/e2sm-v5.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_NRFrequencyBand_List_H_
#define	_NRFrequencyBand_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NRFrequencyBandItem;

/* NRFrequencyBand-List */
typedef struct NRFrequencyBand_List {
	A_SEQUENCE_OF(struct NRFrequencyBandItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRFrequencyBand_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRFrequencyBand_List;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NRFrequencyBandItem.h"

#endif	/* _NRFrequencyBand_List_H_ */
#include <asn_internal.h>
