/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../e2sm_v5.00/e2sm-v5.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#include "NRFrequencyInfo.h"

static asn_TYPE_member_t asn_MBR_NRFrequencyInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NRFrequencyInfo, nrARFCN),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_ARFCN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"nrARFCN"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NRFrequencyInfo, frequencyBand_List),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRFrequencyBand_List,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"frequencyBand-List"
		},
	{ ATF_POINTER, 1, offsetof(struct NRFrequencyInfo, frequencyShift7p5khz),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NRFrequencyShift7p5khz,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"frequencyShift7p5khz"
		},
};
static const ber_tlv_tag_t asn_DEF_NRFrequencyInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NRFrequencyInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nrARFCN */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* frequencyBand-List */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* frequencyShift7p5khz */
};
static asn_SEQUENCE_specifics_t asn_SPC_NRFrequencyInfo_specs_1 = {
	sizeof(struct NRFrequencyInfo),
	offsetof(struct NRFrequencyInfo, _asn_ctx),
	asn_MAP_NRFrequencyInfo_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_NRFrequencyInfo = {
	"NRFrequencyInfo",
	"NRFrequencyInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_NRFrequencyInfo_tags_1,
	sizeof(asn_DEF_NRFrequencyInfo_tags_1)
		/sizeof(asn_DEF_NRFrequencyInfo_tags_1[0]), /* 1 */
	asn_DEF_NRFrequencyInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_NRFrequencyInfo_tags_1)
		/sizeof(asn_DEF_NRFrequencyInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_NRFrequencyInfo_1,
	3,	/* Elements count */
	&asn_SPC_NRFrequencyInfo_specs_1	/* Additional specs */
};

