/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_CoreCPID;
extern struct asn_TYPE_descriptor_s asn_DEF_InterfaceIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_Interface_MessageID;
extern struct asn_TYPE_descriptor_s asn_DEF_InterfaceType;
extern struct asn_TYPE_descriptor_s asn_DEF_GroupID;
extern struct asn_TYPE_descriptor_s asn_DEF_PartialUEID;
extern struct asn_TYPE_descriptor_s asn_DEF_QoSID;
extern struct asn_TYPE_descriptor_s asn_DEF_RRC_MessageID;
extern struct asn_TYPE_descriptor_s asn_DEF_ServingCell_ARFCN;
extern struct asn_TYPE_descriptor_s asn_DEF_ServingCell_PCI;
extern struct asn_TYPE_descriptor_s asn_DEF_SubscriberProfileIDforRFP;
extern struct asn_TYPE_descriptor_s asn_DEF_E_UTRA_TAC;
extern struct asn_TYPE_descriptor_s asn_DEF_IndexToRFSP;
extern struct asn_TYPE_descriptor_s asn_DEF_FiveGS_TAC;
extern struct asn_TYPE_descriptor_s asn_DEF_FreqBandNrItem;
extern struct asn_TYPE_descriptor_s asn_DEF_NRFrequencyInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_EventTriggerDefinition;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_ActionDefinition;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_IndicationHeader;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_IndicationMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_RANfunction_Description;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module E2SM-COMMON-IEs in ../asn1/e2sm-v5.00.asn */
	&asn_DEF_CoreCPID,	
	&asn_DEF_InterfaceIdentifier,	
	&asn_DEF_Interface_MessageID,	
	&asn_DEF_InterfaceType,	
	&asn_DEF_GroupID,	
	&asn_DEF_PartialUEID,	
	&asn_DEF_QoSID,	
	&asn_DEF_RRC_MessageID,	
	&asn_DEF_ServingCell_ARFCN,	
	&asn_DEF_ServingCell_PCI,	
	&asn_DEF_SubscriberProfileIDforRFP,	
	&asn_DEF_E_UTRA_TAC,	
	&asn_DEF_IndexToRFSP,	
	&asn_DEF_FiveGS_TAC,	
	&asn_DEF_FreqBandNrItem,	
	&asn_DEF_NRFrequencyInfo,	
	/* From module E2SM-KPM-IEs in ../asn1/e2sm-kpm-v4.00.asn */
	&asn_DEF_E2SM_KPM_EventTriggerDefinition,	
	&asn_DEF_E2SM_KPM_ActionDefinition,	
	&asn_DEF_E2SM_KPM_IndicationHeader,	
	&asn_DEF_E2SM_KPM_IndicationMessage,	
	&asn_DEF_E2SM_KPM_RANfunction_Description,	
	0
};

