/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../e2sm_v5.00/e2sm-v5.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_RNTI_Value_H_
#define	_RNTI_Value_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RNTI-Value */
typedef long	 RNTI_Value_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RNTI_Value;
asn_struct_free_f RNTI_Value_free;
asn_struct_print_f RNTI_Value_print;
asn_constr_check_f RNTI_Value_constraint;
ber_type_decoder_f RNTI_Value_decode_ber;
der_type_encoder_f RNTI_Value_encode_der;
xer_type_decoder_f RNTI_Value_decode_xer;
xer_type_encoder_f RNTI_Value_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RNTI_Value_H_ */
#include <asn_internal.h>
