/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../e2sm_v5.00/e2sm-v5.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_SupportedSULBandList_H_
#define	_SupportedSULBandList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SupportedSULFreqBandItem;

/* SupportedSULBandList */
typedef struct SupportedSULBandList {
	A_SEQUENCE_OF(struct SupportedSULFreqBandItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SupportedSULBandList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SupportedSULBandList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SupportedSULFreqBandItem.h"

#endif	/* _SupportedSULBandList_H_ */
#include <asn_internal.h>
