/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../e2sm_v5.00/e2sm-v5.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#include "UEID-GNB-CU-UP.h"

static asn_TYPE_member_t asn_MBR_UEID_GNB_CU_UP_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UEID_GNB_CU_UP, gNB_CU_CP_UE_E1AP_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GNB_CU_CP_UE_E1AP_ID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"gNB-CU-CP-UE-E1AP-ID"
		},
	{ ATF_POINTER, 1, offsetof(struct UEID_GNB_CU_UP, ran_UEID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANUEID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"ran-UEID"
		},
};
static const ber_tlv_tag_t asn_DEF_UEID_GNB_CU_UP_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UEID_GNB_CU_UP_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gNB-CU-CP-UE-E1AP-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ran-UEID */
};
static asn_SEQUENCE_specifics_t asn_SPC_UEID_GNB_CU_UP_specs_1 = {
	sizeof(struct UEID_GNB_CU_UP),
	offsetof(struct UEID_GNB_CU_UP, _asn_ctx),
	asn_MAP_UEID_GNB_CU_UP_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* Start extensions */
	3	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_UEID_GNB_CU_UP = {
	"UEID-GNB-CU-UP",
	"UEID-GNB-CU-UP",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_UEID_GNB_CU_UP_tags_1,
	sizeof(asn_DEF_UEID_GNB_CU_UP_tags_1)
		/sizeof(asn_DEF_UEID_GNB_CU_UP_tags_1[0]), /* 1 */
	asn_DEF_UEID_GNB_CU_UP_tags_1,	/* Same as above */
	sizeof(asn_DEF_UEID_GNB_CU_UP_tags_1)
		/sizeof(asn_DEF_UEID_GNB_CU_UP_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_UEID_GNB_CU_UP_1,
	2,	/* Elements count */
	&asn_SPC_UEID_GNB_CU_UP_specs_1	/* Additional specs */
};

