/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../e2sm_v5.00/e2sm-v5.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_UEID_H_
#define	_UEID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UEID-GNB.h"
#include "UEID-GNB-DU.h"
#include "UEID-GNB-CU-UP.h"
#include "UEID-NG-ENB.h"
#include "UEID-NG-ENB-DU.h"
#include "UEID-EN-GNB.h"
#include "UEID-ENB.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UEID_PR {
	UEID_PR_NOTHING,	/* No components present */
	UEID_PR_gNB_UEID,
	UEID_PR_gNB_DU_UEID,
	UEID_PR_gNB_CU_UP_UEID,
	UEID_PR_ng_eNB_UEID,
	UEID_PR_ng_eNB_DU_UEID,
	UEID_PR_en_gNB_UEID,
	UEID_PR_eNB_UEID,
	/* Extensions may appear below */
	
} UEID_PR;

/* UEID */
typedef struct UEID {
	UEID_PR present;
	union UEID_u {
		UEID_GNB_t	 gNB_UEID;
		UEID_GNB_DU_t	 gNB_DU_UEID;
		UEID_GNB_CU_UP_t	 gNB_CU_UP_UEID;
		UEID_NG_ENB_t	 ng_eNB_UEID;
		UEID_NG_ENB_DU_t	 ng_eNB_DU_UEID;
		UEID_EN_GNB_t	 en_gNB_UEID;
		UEID_ENB_t	 eNB_UEID;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEID;

#ifdef __cplusplus
}
#endif

#endif	/* _UEID_H_ */
#include <asn_internal.h>
