/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../e2sm_v5.00/e2sm-v5.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#include "UEID-GNB.h"

static asn_TYPE_member_t asn_MBR_UEID_GNB_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UEID_GNB, amf_UE_NGAP_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AMF_UE_NGAP_ID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"amf-UE-NGAP-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UEID_GNB, guami),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GUAMI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"guami"
		},
	{ ATF_POINTER, 7, offsetof(struct UEID_GNB, gNB_CU_UE_F1AP_ID_List),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UEID_GNB_CU_F1AP_ID_List,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"gNB-CU-UE-F1AP-ID-List"
		},
	{ ATF_POINTER, 6, offsetof(struct UEID_GNB, gNB_CU_CP_UE_E1AP_ID_List),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UEID_GNB_CU_CP_E1AP_ID_List,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"gNB-CU-CP-UE-E1AP-ID-List"
		},
	{ ATF_POINTER, 5, offsetof(struct UEID_GNB, ran_UEID),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANUEID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"ran-UEID"
		},
	{ ATF_POINTER, 4, offsetof(struct UEID_GNB, m_NG_RAN_UE_XnAP_ID),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NG_RANnodeUEXnAPID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"m-NG-RAN-UE-XnAP-ID"
		},
	{ ATF_POINTER, 3, offsetof(struct UEID_GNB, globalGNB_ID),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GlobalGNB_ID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"globalGNB-ID"
		},
	{ ATF_POINTER, 2, offsetof(struct UEID_GNB, globalNG_RANNode_ID),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GlobalNGRANNodeID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"globalNG-RANNode-ID"
		},
	{ ATF_POINTER, 1, offsetof(struct UEID_GNB, cell_RNTI),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Cell_RNTI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not lib, use -gen-PER */
		0,
		"cell-RNTI"
		},
};
static const ber_tlv_tag_t asn_DEF_UEID_GNB_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UEID_GNB_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* amf-UE-NGAP-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* guami */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* gNB-CU-UE-F1AP-ID-List */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* gNB-CU-CP-UE-E1AP-ID-List */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ran-UEID */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* m-NG-RAN-UE-XnAP-ID */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* globalGNB-ID */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* globalNG-RANNode-ID */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 } /* cell-RNTI */
};
static asn_SEQUENCE_specifics_t asn_SPC_UEID_GNB_specs_1 = {
	sizeof(struct UEID_GNB),
	offsetof(struct UEID_GNB, _asn_ctx),
	asn_MAP_UEID_GNB_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	6,	/* Start extensions */
	10	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_UEID_GNB = {
	"UEID-GNB",
	"UEID-GNB",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_UEID_GNB_tags_1,
	sizeof(asn_DEF_UEID_GNB_tags_1)
		/sizeof(asn_DEF_UEID_GNB_tags_1[0]), /* 1 */
	asn_DEF_UEID_GNB_tags_1,	/* Same as above */
	sizeof(asn_DEF_UEID_GNB_tags_1)
		/sizeof(asn_DEF_UEID_GNB_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_UEID_GNB_1,
	9,	/* Elements count */
	&asn_SPC_UEID_GNB_specs_1	/* Additional specs */
};

