/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../e2sm_v5.00/e2sm-v5.00.asn1"
 * 	`asn1c -fnative-types -fcompound-names`
 */

#ifndef	_UEID_GNB_CU_CP_E1AP_ID_List_H_
#define	_UEID_GNB_CU_CP_E1AP_ID_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UEID_GNB_CU_CP_E1AP_ID_Item;

/* UEID-GNB-CU-CP-E1AP-ID-List */
typedef struct UEID_GNB_CU_CP_E1AP_ID_List {
	A_SEQUENCE_OF(struct UEID_GNB_CU_CP_E1AP_ID_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEID_GNB_CU_CP_E1AP_ID_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEID_GNB_CU_CP_E1AP_ID_List;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UEID-GNB-CU-CP-E1AP-ID-Item.h"

#endif	/* _UEID_GNB_CU_CP_E1AP_ID_List_H_ */
#include <asn_internal.h>
