// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protobuf/xapp.proto
#ifndef GRPC_protobuf_2fxapp_2eproto__INCLUDED
#define GRPC_protobuf_2fxapp_2eproto__INCLUDED

#include "protobuf/xapp.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace xapp {

// ------------------------------------//
// ------------- Services ------------//
// ----------------------------------//
//
class E2SM_KPM_Service final {
 public:
  static constexpr char const* service_full_name() {
    return "xapp.E2SM_KPM_Service";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::xapp::KPMIndicationResponse>> GetIndicationStream(::grpc::ClientContext* context, const ::xapp::KPMIndicationRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::xapp::KPMIndicationResponse>>(GetIndicationStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::xapp::KPMIndicationResponse>> AsyncGetIndicationStream(::grpc::ClientContext* context, const ::xapp::KPMIndicationRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::xapp::KPMIndicationResponse>>(AsyncGetIndicationStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::xapp::KPMIndicationResponse>> PrepareAsyncGetIndicationStream(::grpc::ClientContext* context, const ::xapp::KPMIndicationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::xapp::KPMIndicationResponse>>(PrepareAsyncGetIndicationStreamRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetIndicationStream(::grpc::ClientContext* context, const ::xapp::KPMIndicationRequest* request, ::grpc::ClientReadReactor< ::xapp::KPMIndicationResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::xapp::KPMIndicationResponse>* GetIndicationStreamRaw(::grpc::ClientContext* context, const ::xapp::KPMIndicationRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::xapp::KPMIndicationResponse>* AsyncGetIndicationStreamRaw(::grpc::ClientContext* context, const ::xapp::KPMIndicationRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::xapp::KPMIndicationResponse>* PrepareAsyncGetIndicationStreamRaw(::grpc::ClientContext* context, const ::xapp::KPMIndicationRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::xapp::KPMIndicationResponse>> GetIndicationStream(::grpc::ClientContext* context, const ::xapp::KPMIndicationRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::xapp::KPMIndicationResponse>>(GetIndicationStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::xapp::KPMIndicationResponse>> AsyncGetIndicationStream(::grpc::ClientContext* context, const ::xapp::KPMIndicationRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::xapp::KPMIndicationResponse>>(AsyncGetIndicationStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::xapp::KPMIndicationResponse>> PrepareAsyncGetIndicationStream(::grpc::ClientContext* context, const ::xapp::KPMIndicationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::xapp::KPMIndicationResponse>>(PrepareAsyncGetIndicationStreamRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetIndicationStream(::grpc::ClientContext* context, const ::xapp::KPMIndicationRequest* request, ::grpc::ClientReadReactor< ::xapp::KPMIndicationResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::xapp::KPMIndicationResponse>* GetIndicationStreamRaw(::grpc::ClientContext* context, const ::xapp::KPMIndicationRequest& request) override;
    ::grpc::ClientAsyncReader< ::xapp::KPMIndicationResponse>* AsyncGetIndicationStreamRaw(::grpc::ClientContext* context, const ::xapp::KPMIndicationRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::xapp::KPMIndicationResponse>* PrepareAsyncGetIndicationStreamRaw(::grpc::ClientContext* context, const ::xapp::KPMIndicationRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetIndicationStream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetIndicationStream(::grpc::ServerContext* context, const ::xapp::KPMIndicationRequest* request, ::grpc::ServerWriter< ::xapp::KPMIndicationResponse>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetIndicationStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetIndicationStream() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetIndicationStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIndicationStream(::grpc::ServerContext* /*context*/, const ::xapp::KPMIndicationRequest* /*request*/, ::grpc::ServerWriter< ::xapp::KPMIndicationResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetIndicationStream(::grpc::ServerContext* context, ::xapp::KPMIndicationRequest* request, ::grpc::ServerAsyncWriter< ::xapp::KPMIndicationResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetIndicationStream<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetIndicationStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetIndicationStream() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::xapp::KPMIndicationRequest, ::xapp::KPMIndicationResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::xapp::KPMIndicationRequest* request) { return this->GetIndicationStream(context, request); }));
    }
    ~WithCallbackMethod_GetIndicationStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIndicationStream(::grpc::ServerContext* /*context*/, const ::xapp::KPMIndicationRequest* /*request*/, ::grpc::ServerWriter< ::xapp::KPMIndicationResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::xapp::KPMIndicationResponse>* GetIndicationStream(
      ::grpc::CallbackServerContext* /*context*/, const ::xapp::KPMIndicationRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetIndicationStream<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetIndicationStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetIndicationStream() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetIndicationStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIndicationStream(::grpc::ServerContext* /*context*/, const ::xapp::KPMIndicationRequest* /*request*/, ::grpc::ServerWriter< ::xapp::KPMIndicationResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetIndicationStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetIndicationStream() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetIndicationStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIndicationStream(::grpc::ServerContext* /*context*/, const ::xapp::KPMIndicationRequest* /*request*/, ::grpc::ServerWriter< ::xapp::KPMIndicationResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetIndicationStream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetIndicationStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetIndicationStream() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->GetIndicationStream(context, request); }));
    }
    ~WithRawCallbackMethod_GetIndicationStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIndicationStream(::grpc::ServerContext* /*context*/, const ::xapp::KPMIndicationRequest* /*request*/, ::grpc::ServerWriter< ::xapp::KPMIndicationResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* GetIndicationStream(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_GetIndicationStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_GetIndicationStream() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::xapp::KPMIndicationRequest, ::xapp::KPMIndicationResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::xapp::KPMIndicationRequest, ::xapp::KPMIndicationResponse>* streamer) {
                       return this->StreamedGetIndicationStream(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_GetIndicationStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetIndicationStream(::grpc::ServerContext* /*context*/, const ::xapp::KPMIndicationRequest* /*request*/, ::grpc::ServerWriter< ::xapp::KPMIndicationResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedGetIndicationStream(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::xapp::KPMIndicationRequest,::xapp::KPMIndicationResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_GetIndicationStream<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_GetIndicationStream<Service > StreamedService;
};

}  // namespace xapp


#endif  // GRPC_protobuf_2fxapp_2eproto__INCLUDED
