name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          muriloavlis/usap
        # generate Docker tags based on the following events/attributes
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
            
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set Image Labels
      run: |
        IMG_VER=$(git branch --show-current)
        IMG_BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        IMG_VCS_REF=$(git rev-parse --short HEAD)
        echo "IMG_VER=${IMG_VER}" >> $GITHUB_ENV
        echo "IMG_BUILD_DATE=${IMG_BUILD_DATE}" >> $GITHUB_ENV
        echo "IMG_VCS_REF=${IMG_VCS_REF}" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: "docker/Dockerfile.usap"
        push: true
        build-args: |
          VERSION=${{ env.IMG_VER }}
          BUILD_DATE=${{ env.IMG_BUILD_DATE }}
          VCS_REF=${{ env.IMG_VCS_REF }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
