/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../asn/e2sm-v5.00.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_InterfaceIdentifier_H_
#define	_InterfaceIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InterfaceID-NG.h"
#include "InterfaceID-Xn.h"
#include "InterfaceID-F1.h"
#include "InterfaceID-E1.h"
#include "InterfaceID-S1.h"
#include "InterfaceID-X2.h"
#include "InterfaceID-W1.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum InterfaceIdentifier_PR {
	InterfaceIdentifier_PR_NOTHING,	/* No components present */
	InterfaceIdentifier_PR_nG,
	InterfaceIdentifier_PR_xN,
	InterfaceIdentifier_PR_f1,
	InterfaceIdentifier_PR_e1,
	InterfaceIdentifier_PR_s1,
	InterfaceIdentifier_PR_x2,
	InterfaceIdentifier_PR_w1
	/* Extensions may appear below */
	
} InterfaceIdentifier_PR;

/* InterfaceIdentifier */
typedef struct InterfaceIdentifier {
	InterfaceIdentifier_PR present;
	union InterfaceIdentifier_u {
		InterfaceID_NG_t	 nG;
		InterfaceID_Xn_t	 xN;
		InterfaceID_F1_t	 f1;
		InterfaceID_E1_t	 e1;
		InterfaceID_S1_t	 s1;
		InterfaceID_X2_t	 x2;
		InterfaceID_W1_t	 w1;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterfaceIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterfaceIdentifier;

#ifdef __cplusplus
}
#endif

#endif	/* _InterfaceIdentifier_H_ */
#include <asn_internal.h>
